import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from '../Components/SessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '../pages/api/auth/[...nextauth]';
import Login from '../Components/Login';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
			<body className={inter.className}>
				<SessionProvider session={session}>
					{!session ? (
						<Login />
					) : (
						<div className='flex'>
							<div className='bg-[#242424] content-center'>{children}</div>
						</div>
					)}
				</SessionProvider>
			</body>
    </html>
  )
}